###CONFIGURACION PRETTIER
#bracketSpacing: true
useEditorConfig: false
###RANGE, PARSE ????
printWidth: 120 # Specify the line length that the printer will wrap on.
#semi: true # Print semicolons at the ends of statements.
#bracketSpacing: true #Print spaces between brackets in object literals.
arrowParens: 'always' # Include parentheses around a sole arrow function parameter.
tabWidth: 4 # Specify the number of spaces per indentation-level.
useTabs: false # Indent lines with tabs instead of spaces.
singleQuote: true # Use single quotes instead of double quotes.
quoteProps: 'as-needed' # Change when properties in objects are quoted.
jsxSingleQuote: true # Use single quotes instead of double quotes in JSX.
trailingComma: 'es5' # Print trailing commas wherever possible when multi-line
jsxBracketSameLine: true # Put the > of a multi-line JSX element at the end of the last line.
